---
language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

matrix:
  fast_finish: true

before_install:
  - python3 --version
  - pip install --user -r requirements.txt
  - export MAVEN_SKIP_RC=true
  - export MAVEN_OPTS=-Dpython=python3
