---
language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk11
  - oraclejdk11
  - openjdk8
  - oraclejdk8

matrix:
  fast_finish: true

before_install:
  pip install --user -r requirements.txt
