---
name: Maven

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        java: [8, 11, 17, 21]
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        exclude:
          - java: 8
            python-version: '3.9'
          - java: 8
            python-version: '3.10'
          - java: 8
            python-version: '3.11'
          - java: 8
            python-version: '3.12'
          - java: 8
            python-version: '3.13'
          - java: 17
            python-version: '3.9'
          - java: 17
            python-version: '3.10'
          - java: 17
            python-version: '3.11'
          - java: 17
            python-version: '3.12'
          - java: 17
            python-version: '3.13'
          - java: 21
            python-version: '3.9'
          - java: 21
            python-version: '3.10'
          - java: 21
            python-version: '3.11'
          - java: 21
            python-version: '3.12'
          - java: 21
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    env:
      maven_commands: install
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build
        run: mvn ${{ env.maven_commands }}
